/**
 *
 * This type is derived from https://schema.org/OnDemandEvent, which means that any of this type's properties within schema.org may also be used.
 */
export const OnDemandEvent: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "OnDemandEvent";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    '@id'?: string | undefined;
    accessibilityInformation?: string | undefined;
    accessibilitySupport?: any[] | undefined;
    activity?: any[] | undefined;
    additionalAdmissionRestriction?: string[] | undefined;
    ageRange?: any;
    ageRestriction?: any;
    attendeeInstructions?: string | undefined;
    category?: any[] | string[] | undefined;
    contributor?: any[] | undefined;
    duration?: string | undefined;
    genderRestriction?: any;
    image?: any[] | undefined;
    isAccessibleForFree?: boolean | undefined;
    isCoached?: boolean | undefined;
    leader?: any[] | undefined;
    level?: any[] | string[] | undefined;
    offers?: any[] | undefined;
    organizer?: any;
    programme?: any;
    superEvent?: any;
    url?: string | undefined;
    workFeatured?: any;
    formattedDescription?: string | undefined;
    distance?: any;
    attendeeCount?: number | undefined;
    registrationCount?: number | undefined;
    isWheelchairAccessible?: boolean | undefined;
    estimatedDuration?: any;
    video?: any[] | undefined;
    sportsActivityLocation?: any[] | undefined;
    offerValidityPeriod?: string | undefined;
    facilitySetting?: any;
    isVirtuallyCoached?: boolean | undefined;
    virtualLocation?: any;
    affiliatedLocation?: any;
    isInteractivityPreferred?: boolean | undefined;
    participantSuppliedEquipment?: any;
    donationPaymentUrl?: string | undefined;
    isFirstSessionAccessibleForFree?: boolean | undefined;
    contactPoint?: any;
    bookingChannel?: any[] | undefined;
    testOpportunityCriteria?: any;
}, {
    '@type': "OnDemandEvent";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    '@id'?: string | undefined;
    accessibilityInformation?: string | undefined;
    accessibilitySupport?: any[] | undefined;
    activity?: any[] | undefined;
    additionalAdmissionRestriction?: string[] | undefined;
    ageRange?: any;
    ageRestriction?: any;
    attendeeInstructions?: string | undefined;
    category?: any[] | string[] | undefined;
    contributor?: any[] | undefined;
    duration?: string | undefined;
    genderRestriction?: any;
    image?: any[] | undefined;
    isAccessibleForFree?: boolean | undefined;
    isCoached?: boolean | undefined;
    leader?: any[] | undefined;
    level?: any[] | string[] | undefined;
    offers?: any[] | undefined;
    organizer?: any;
    programme?: any;
    superEvent?: any;
    url?: string | undefined;
    workFeatured?: any;
    formattedDescription?: string | undefined;
    distance?: any;
    attendeeCount?: number | undefined;
    registrationCount?: number | undefined;
    isWheelchairAccessible?: boolean | undefined;
    estimatedDuration?: any;
    video?: any[] | undefined;
    sportsActivityLocation?: any[] | undefined;
    offerValidityPeriod?: string | undefined;
    facilitySetting?: any;
    isVirtuallyCoached?: boolean | undefined;
    virtualLocation?: any;
    affiliatedLocation?: any;
    isInteractivityPreferred?: boolean | undefined;
    participantSuppliedEquipment?: any;
    donationPaymentUrl?: string | undefined;
    isFirstSessionAccessibleForFree?: boolean | undefined;
    contactPoint?: any;
    bookingChannel?: any[] | undefined;
    testOpportunityCriteria?: any;
}>;
