/**
 */
export const BroadcastService: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "BroadcastService";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    broadcastFrequency?: any;
    videoFormat?: string | undefined;
    parentService?: any;
    broadcastDisplayName?: string | undefined;
    broadcastAffiliateOf?: any;
    broadcastTimezone?: string | undefined;
    area?: any;
    broadcaster?: any;
    inLanguage?: any;
    hasBroadcastChannel?: any;
    callSign?: string | undefined;
    aggregateRating?: any;
    serviceOutput?: any;
    isSimilarTo?: any;
    offers?: any;
    broker?: any;
    termsOfService?: string | undefined;
    award?: string | undefined;
    provider?: any;
    review?: any;
    areaServed?: any;
    serviceAudience?: any;
    hasOfferCatalog?: any;
    produces?: any;
    logo?: any;
    availableChannel?: any;
    category?: any;
    serviceType?: any;
    slogan?: string | undefined;
    hoursAvailable?: any;
    serviceArea?: any;
    brand?: any;
    audience?: any;
    isRelatedTo?: any;
    providerMobility?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "BroadcastService";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    broadcastFrequency?: any;
    videoFormat?: string | undefined;
    parentService?: any;
    broadcastDisplayName?: string | undefined;
    broadcastAffiliateOf?: any;
    broadcastTimezone?: string | undefined;
    area?: any;
    broadcaster?: any;
    inLanguage?: any;
    hasBroadcastChannel?: any;
    callSign?: string | undefined;
    aggregateRating?: any;
    serviceOutput?: any;
    isSimilarTo?: any;
    offers?: any;
    broker?: any;
    termsOfService?: string | undefined;
    award?: string | undefined;
    provider?: any;
    review?: any;
    areaServed?: any;
    serviceAudience?: any;
    hasOfferCatalog?: any;
    produces?: any;
    logo?: any;
    availableChannel?: any;
    category?: any;
    serviceType?: any;
    slogan?: string | undefined;
    hoursAvailable?: any;
    serviceArea?: any;
    brand?: any;
    audience?: any;
    isRelatedTo?: any;
    providerMobility?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
