/**
 */
export const BusOrCoach: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "BusOrCoach";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    roofLoad?: any;
    acrissCode?: string | undefined;
    vehicleModelDate?: string | undefined;
    payload?: any;
    vehicleTransmission?: any;
    numberOfDoors?: any;
    modelDate?: string | undefined;
    fuelEfficiency?: any;
    fuelType?: any;
    bodyType?: any;
    wheelbase?: any;
    vehicleInteriorType?: string | undefined;
    tongueWeight?: any;
    vehicleEngine?: any;
    dateVehicleFirstRegistered?: string | undefined;
    speed?: any;
    driveWheelConfiguration?: any;
    seatingCapacity?: any;
    fuelCapacity?: any;
    cargoVolume?: any;
    vehicleIdentificationNumber?: string | undefined;
    vehicleSpecialUsage?: any;
    emissionsCO2?: number | undefined;
    vehicleSeatingCapacity?: any;
    trailerWeight?: any;
    numberOfPreviousOwners?: any;
    purchaseDate?: string | undefined;
    knownVehicleDamages?: string | undefined;
    mileageFromOdometer?: any;
    fuelConsumption?: any;
    numberOfAxles?: any;
    steeringPosition?: any;
    accelerationTime?: any;
    vehicleConfiguration?: string | undefined;
    numberOfAirbags?: string | number | undefined;
    weightTotal?: any;
    meetsEmissionStandard?: any;
    productionDate?: string | undefined;
    callSign?: string | undefined;
    vehicleInteriorColor?: string | undefined;
    numberOfForwardGears?: any;
    hasMeasurement?: any;
    itemCondition?: any;
    aggregateRating?: any;
    size?: any;
    depth?: any;
    height?: any;
    gtin12?: string | undefined;
    isSimilarTo?: any;
    weight?: any;
    hasMerchantReturnPolicy?: any;
    offers?: any;
    width?: any;
    isConsumableFor?: any;
    reviews?: any;
    award?: string | undefined;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    review?: any;
    hasEnergyConsumptionDetails?: any;
    color?: string | undefined;
    additionalProperty?: any;
    logo?: any;
    mpn?: string | undefined;
    inProductGroupWithID?: string | undefined;
    category?: any;
    isVariantOf?: any;
    slogan?: string | undefined;
    pattern?: any;
    sku?: string | undefined;
    nsn?: string | undefined;
    gtin14?: string | undefined;
    isAccessoryOrSparePartFor?: any;
    manufacturer?: any;
    model?: any;
    brand?: any;
    releaseDate?: string | undefined;
    gtin8?: string | undefined;
    material?: any;
    awards?: string | undefined;
    audience?: any;
    isRelatedTo?: any;
    productID?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "BusOrCoach";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    roofLoad?: any;
    acrissCode?: string | undefined;
    vehicleModelDate?: string | undefined;
    payload?: any;
    vehicleTransmission?: any;
    numberOfDoors?: any;
    modelDate?: string | undefined;
    fuelEfficiency?: any;
    fuelType?: any;
    bodyType?: any;
    wheelbase?: any;
    vehicleInteriorType?: string | undefined;
    tongueWeight?: any;
    vehicleEngine?: any;
    dateVehicleFirstRegistered?: string | undefined;
    speed?: any;
    driveWheelConfiguration?: any;
    seatingCapacity?: any;
    fuelCapacity?: any;
    cargoVolume?: any;
    vehicleIdentificationNumber?: string | undefined;
    vehicleSpecialUsage?: any;
    emissionsCO2?: number | undefined;
    vehicleSeatingCapacity?: any;
    trailerWeight?: any;
    numberOfPreviousOwners?: any;
    purchaseDate?: string | undefined;
    knownVehicleDamages?: string | undefined;
    mileageFromOdometer?: any;
    fuelConsumption?: any;
    numberOfAxles?: any;
    steeringPosition?: any;
    accelerationTime?: any;
    vehicleConfiguration?: string | undefined;
    numberOfAirbags?: string | number | undefined;
    weightTotal?: any;
    meetsEmissionStandard?: any;
    productionDate?: string | undefined;
    callSign?: string | undefined;
    vehicleInteriorColor?: string | undefined;
    numberOfForwardGears?: any;
    hasMeasurement?: any;
    itemCondition?: any;
    aggregateRating?: any;
    size?: any;
    depth?: any;
    height?: any;
    gtin12?: string | undefined;
    isSimilarTo?: any;
    weight?: any;
    hasMerchantReturnPolicy?: any;
    offers?: any;
    width?: any;
    isConsumableFor?: any;
    reviews?: any;
    award?: string | undefined;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    review?: any;
    hasEnergyConsumptionDetails?: any;
    color?: string | undefined;
    additionalProperty?: any;
    logo?: any;
    mpn?: string | undefined;
    inProductGroupWithID?: string | undefined;
    category?: any;
    isVariantOf?: any;
    slogan?: string | undefined;
    pattern?: any;
    sku?: string | undefined;
    nsn?: string | undefined;
    gtin14?: string | undefined;
    isAccessoryOrSparePartFor?: any;
    manufacturer?: any;
    model?: any;
    brand?: any;
    releaseDate?: string | undefined;
    gtin8?: string | undefined;
    material?: any;
    awards?: string | undefined;
    audience?: any;
    isRelatedTo?: any;
    productID?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
