/**
 */
export const CivicStructure: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "CivicStructure";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    openingHours?: string | undefined;
    aggregateRating?: any;
    geoIntersects?: any;
    photos?: any;
    address?: any;
    tourBookingPage?: string | undefined;
    longitude?: string | number | undefined;
    geo?: any;
    globalLocationNumber?: string | undefined;
    geoCoveredBy?: any;
    containedInPlace?: any;
    specialOpeningHoursSpecification?: any;
    geoOverlaps?: any;
    photo?: any;
    isicV4?: string | undefined;
    reviews?: any;
    review?: any;
    events?: any;
    openingHoursSpecification?: any;
    geoWithin?: any;
    hasDriveThroughService?: boolean | undefined;
    containedIn?: any;
    geoCovers?: any;
    map?: string | undefined;
    amenityFeature?: any;
    event?: any;
    additionalProperty?: any;
    telephone?: string | undefined;
    logo?: any;
    isAccessibleForFree?: boolean | undefined;
    maximumAttendeeCapacity?: number | undefined;
    slogan?: string | undefined;
    maps?: string | undefined;
    hasMap?: any;
    geoEquals?: any;
    containsPlace?: any;
    geoDisjoint?: any;
    latitude?: string | number | undefined;
    smokingAllowed?: boolean | undefined;
    faxNumber?: string | undefined;
    branchCode?: string | undefined;
    geoTouches?: any;
    geoCrosses?: any;
    geoContains?: any;
    publicAccess?: boolean | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "CivicStructure";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    openingHours?: string | undefined;
    aggregateRating?: any;
    geoIntersects?: any;
    photos?: any;
    address?: any;
    tourBookingPage?: string | undefined;
    longitude?: string | number | undefined;
    geo?: any;
    globalLocationNumber?: string | undefined;
    geoCoveredBy?: any;
    containedInPlace?: any;
    specialOpeningHoursSpecification?: any;
    geoOverlaps?: any;
    photo?: any;
    isicV4?: string | undefined;
    reviews?: any;
    review?: any;
    events?: any;
    openingHoursSpecification?: any;
    geoWithin?: any;
    hasDriveThroughService?: boolean | undefined;
    containedIn?: any;
    geoCovers?: any;
    map?: string | undefined;
    amenityFeature?: any;
    event?: any;
    additionalProperty?: any;
    telephone?: string | undefined;
    logo?: any;
    isAccessibleForFree?: boolean | undefined;
    maximumAttendeeCapacity?: number | undefined;
    slogan?: string | undefined;
    maps?: string | undefined;
    hasMap?: any;
    geoEquals?: any;
    containsPlace?: any;
    geoDisjoint?: any;
    latitude?: string | number | undefined;
    smokingAllowed?: boolean | undefined;
    faxNumber?: string | undefined;
    branchCode?: string | undefined;
    geoTouches?: any;
    geoCrosses?: any;
    geoContains?: any;
    publicAccess?: boolean | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
