/**
 */
export const CourseInstance: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "CourseInstance";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    courseMode?: string | undefined;
    courseWorkload?: string | undefined;
    instructor?: any;
    workFeatured?: any;
    aggregateRating?: any;
    workPerformed?: any;
    eventSchedule?: any;
    attendees?: any;
    contributor?: any;
    actor?: any;
    performer?: any;
    offers?: any;
    startDate?: string | undefined;
    director?: any;
    previousStartDate?: string | undefined;
    review?: any;
    translator?: any;
    organizer?: any;
    subEvents?: any;
    sponsor?: any;
    isAccessibleForFree?: boolean | undefined;
    maximumAttendeeCapacity?: number | undefined;
    eventStatus?: any;
    maximumPhysicalAttendeeCapacity?: number | undefined;
    subEvent?: any;
    endDate?: string | undefined;
    attendee?: any;
    recordedIn?: any;
    about?: any;
    inLanguage?: any;
    superEvent?: any;
    eventAttendanceMode?: any;
    composer?: any;
    performers?: any;
    duration?: string | undefined;
    doorTime?: string | undefined;
    funder?: any;
    remainingAttendeeCapacity?: number | undefined;
    location?: any;
    audience?: any;
    maximumVirtualAttendeeCapacity?: number | undefined;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "CourseInstance";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    courseMode?: string | undefined;
    courseWorkload?: string | undefined;
    instructor?: any;
    workFeatured?: any;
    aggregateRating?: any;
    workPerformed?: any;
    eventSchedule?: any;
    attendees?: any;
    contributor?: any;
    actor?: any;
    performer?: any;
    offers?: any;
    startDate?: string | undefined;
    director?: any;
    previousStartDate?: string | undefined;
    review?: any;
    translator?: any;
    organizer?: any;
    subEvents?: any;
    sponsor?: any;
    isAccessibleForFree?: boolean | undefined;
    maximumAttendeeCapacity?: number | undefined;
    eventStatus?: any;
    maximumPhysicalAttendeeCapacity?: number | undefined;
    subEvent?: any;
    endDate?: string | undefined;
    attendee?: any;
    recordedIn?: any;
    about?: any;
    inLanguage?: any;
    superEvent?: any;
    eventAttendanceMode?: any;
    composer?: any;
    performers?: any;
    duration?: string | undefined;
    doorTime?: string | undefined;
    funder?: any;
    remainingAttendeeCapacity?: number | undefined;
    location?: any;
    audience?: any;
    maximumVirtualAttendeeCapacity?: number | undefined;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
