/**
 */
export const Demand: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Demand";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    availableDeliveryMethod?: any;
    itemCondition?: any;
    validFrom?: string | undefined;
    seller?: any;
    gtin12?: string | undefined;
    eligibleRegion?: any;
    warranty?: any;
    availabilityEnds?: string | undefined;
    deliveryLeadTime?: any;
    eligibleDuration?: any;
    availabilityStarts?: string | undefined;
    serialNumber?: string | undefined;
    acceptedPaymentMethod?: any;
    priceSpecification?: any;
    eligibleTransactionVolume?: any;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    areaServed?: any;
    advanceBookingRequirement?: any;
    itemOffered?: any;
    inventoryLevel?: any;
    ineligibleRegion?: any;
    mpn?: string | undefined;
    includesObject?: any;
    availability?: any;
    sku?: string | undefined;
    eligibleCustomerType?: any;
    gtin14?: string | undefined;
    eligibleQuantity?: any;
    availableAtOrFrom?: any;
    gtin8?: string | undefined;
    businessFunction?: any;
    validThrough?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Demand";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    availableDeliveryMethod?: any;
    itemCondition?: any;
    validFrom?: string | undefined;
    seller?: any;
    gtin12?: string | undefined;
    eligibleRegion?: any;
    warranty?: any;
    availabilityEnds?: string | undefined;
    deliveryLeadTime?: any;
    eligibleDuration?: any;
    availabilityStarts?: string | undefined;
    serialNumber?: string | undefined;
    acceptedPaymentMethod?: any;
    priceSpecification?: any;
    eligibleTransactionVolume?: any;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    areaServed?: any;
    advanceBookingRequirement?: any;
    itemOffered?: any;
    inventoryLevel?: any;
    ineligibleRegion?: any;
    mpn?: string | undefined;
    includesObject?: any;
    availability?: any;
    sku?: string | undefined;
    eligibleCustomerType?: any;
    gtin14?: string | undefined;
    eligibleQuantity?: any;
    availableAtOrFrom?: any;
    gtin8?: string | undefined;
    businessFunction?: any;
    validThrough?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
