/**
 */
export const Drug: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Drug";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    mechanismOfAction?: string | undefined;
    pregnancyCategory?: any;
    isProprietary?: boolean | undefined;
    includedInHealthInsurancePlan?: any;
    maximumIntake?: any;
    drugClass?: any;
    clinicalPharmacology?: string | undefined;
    rxcui?: string | undefined;
    legalStatus?: any;
    breastfeedingWarning?: string | undefined;
    nonProprietaryName?: string | undefined;
    labelDetails?: string | undefined;
    overdosage?: string | undefined;
    interactingDrug?: any;
    clincalPharmacology?: string | undefined;
    relatedDrug?: any;
    foodWarning?: string | undefined;
    isAvailableGenerically?: boolean | undefined;
    proprietaryName?: string | undefined;
    activeIngredient?: string | undefined;
    administrationRoute?: string | undefined;
    warning?: string | undefined;
    alcoholWarning?: string | undefined;
    manufacturer?: any;
    dosageForm?: string | undefined;
    pregnancyWarning?: string | undefined;
    drugUnit?: string | undefined;
    availableStrength?: any;
    prescribingInfo?: string | undefined;
    prescriptionStatus?: any;
    doseSchedule?: any;
    guideline?: any;
    recognizingAuthority?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Drug";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    mechanismOfAction?: string | undefined;
    pregnancyCategory?: any;
    isProprietary?: boolean | undefined;
    includedInHealthInsurancePlan?: any;
    maximumIntake?: any;
    drugClass?: any;
    clinicalPharmacology?: string | undefined;
    rxcui?: string | undefined;
    legalStatus?: any;
    breastfeedingWarning?: string | undefined;
    nonProprietaryName?: string | undefined;
    labelDetails?: string | undefined;
    overdosage?: string | undefined;
    interactingDrug?: any;
    clincalPharmacology?: string | undefined;
    relatedDrug?: any;
    foodWarning?: string | undefined;
    isAvailableGenerically?: boolean | undefined;
    proprietaryName?: string | undefined;
    activeIngredient?: string | undefined;
    administrationRoute?: string | undefined;
    warning?: string | undefined;
    alcoholWarning?: string | undefined;
    manufacturer?: any;
    dosageForm?: string | undefined;
    pregnancyWarning?: string | undefined;
    drugUnit?: string | undefined;
    availableStrength?: any;
    prescribingInfo?: string | undefined;
    prescriptionStatus?: any;
    doseSchedule?: any;
    guideline?: any;
    recognizingAuthority?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
