/**
 */
export const EducationalOccupationalProgram: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "EducationalOccupationalProgram";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    hasCourse?: any;
    programType?: any;
    trainingSalary?: any;
    applicationStartDate?: string | undefined;
    occupationalCategory?: any;
    offers?: any;
    startDate?: string | undefined;
    provider?: any;
    termsPerYear?: number | undefined;
    salaryUponCompletion?: any;
    occupationalCredentialAwarded?: any;
    financialAidEligible?: any;
    dayOfWeek?: any;
    endDate?: string | undefined;
    educationalProgramMode?: string | undefined;
    maximumEnrollment?: number | undefined;
    termDuration?: string | undefined;
    applicationDeadline?: string | undefined;
    typicalCreditsPerTerm?: any;
    timeToComplete?: string | undefined;
    numberOfCredits?: any;
    timeOfDay?: string | undefined;
    educationalCredentialAwarded?: any;
    programPrerequisites?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "EducationalOccupationalProgram";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    hasCourse?: any;
    programType?: any;
    trainingSalary?: any;
    applicationStartDate?: string | undefined;
    occupationalCategory?: any;
    offers?: any;
    startDate?: string | undefined;
    provider?: any;
    termsPerYear?: number | undefined;
    salaryUponCompletion?: any;
    occupationalCredentialAwarded?: any;
    financialAidEligible?: any;
    dayOfWeek?: any;
    endDate?: string | undefined;
    educationalProgramMode?: string | undefined;
    maximumEnrollment?: number | undefined;
    termDuration?: string | undefined;
    applicationDeadline?: string | undefined;
    typicalCreditsPerTerm?: any;
    timeToComplete?: string | undefined;
    numberOfCredits?: any;
    timeOfDay?: string | undefined;
    educationalCredentialAwarded?: any;
    programPrerequisites?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
