/**
 */
export const ExerciseAction: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "ExerciseAction";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    exerciseCourse?: any;
    fromLocation?: any;
    exerciseType?: string | undefined;
    sportsEvent?: any;
    sportsTeam?: any;
    course?: any;
    diet?: any;
    sportsActivityLocation?: any;
    opponent?: any;
    distance?: any;
    exerciseRelatedDiet?: any;
    exercisePlan?: any;
    toLocation?: any;
    event?: any;
    audience?: any;
    startTime?: string | undefined;
    instrument?: any;
    actionStatus?: any;
    agent?: any;
    participant?: any;
    target?: any;
    endTime?: string | undefined;
    error?: any;
    result?: any;
    object?: any;
    location?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "ExerciseAction";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    exerciseCourse?: any;
    fromLocation?: any;
    exerciseType?: string | undefined;
    sportsEvent?: any;
    sportsTeam?: any;
    course?: any;
    diet?: any;
    sportsActivityLocation?: any;
    opponent?: any;
    distance?: any;
    exerciseRelatedDiet?: any;
    exercisePlan?: any;
    toLocation?: any;
    event?: any;
    audience?: any;
    startTime?: string | undefined;
    instrument?: any;
    actionStatus?: any;
    agent?: any;
    participant?: any;
    target?: any;
    endTime?: string | undefined;
    error?: any;
    result?: any;
    object?: any;
    location?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
