/**
 */
export const ExercisePlan: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "ExercisePlan";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    exerciseType?: string | undefined;
    additionalVariable?: string | undefined;
    workload?: any;
    activityFrequency?: any;
    intensity?: any;
    repetitions?: any;
    activityDuration?: any;
    restPeriods?: any;
    epidemiology?: string | undefined;
    associatedAnatomy?: any;
    category?: any;
    pathophysiology?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "ExercisePlan";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    exerciseType?: string | undefined;
    additionalVariable?: string | undefined;
    workload?: any;
    activityFrequency?: any;
    intensity?: any;
    repetitions?: any;
    activityDuration?: any;
    restPeriods?: any;
    epidemiology?: string | undefined;
    associatedAnatomy?: any;
    category?: any;
    pathophysiology?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
