/**
 */
export const HowToTip: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "HowToTip";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    text?: string | undefined;
    aggregateRating?: any;
    discussionUrl?: string | undefined;
    temporal?: string | undefined;
    conditionsOfAccess?: string | undefined;
    expires?: string | undefined;
    size?: any;
    timeRequired?: string | undefined;
    dateModified?: string | undefined;
    spatialCoverage?: any;
    educationalLevel?: any;
    exampleOfWork?: any;
    copyrightYear?: number | undefined;
    sourceOrganization?: any;
    isPartOf?: any;
    video?: any;
    workTranslation?: any;
    sdPublisher?: any;
    creator?: any;
    thumbnailUrl?: string | undefined;
    translationOfWork?: any;
    contentReferenceTime?: string | undefined;
    datePublished?: string | undefined;
    temporalCoverage?: any;
    fileFormat?: string | undefined;
    contentLocation?: any;
    alternativeHeadline?: string | undefined;
    contributor?: any;
    version?: string | number | undefined;
    accessMode?: string | undefined;
    spatial?: any;
    encoding?: any;
    producer?: any;
    abstract?: string | undefined;
    publication?: any;
    locationCreated?: any;
    maintainer?: any;
    copyrightHolder?: any;
    offers?: any;
    genre?: string | undefined;
    author?: any;
    accessibilitySummary?: string | undefined;
    dateCreated?: string | undefined;
    reviews?: any;
    contentRating?: any;
    accessibilityAPI?: string | undefined;
    publisher?: any;
    license?: any;
    isFamilyFriendly?: boolean | undefined;
    accessibilityHazard?: string | undefined;
    mainEntity?: any;
    award?: string | undefined;
    provider?: any;
    review?: any;
    accountablePerson?: any;
    interactivityType?: string | undefined;
    editEIDR?: string | undefined;
    translator?: any;
    commentCount?: number | undefined;
    schemaVersion?: string | undefined;
    sdDatePublished?: string | undefined;
    educationalUse?: any;
    accessibilityControl?: string | undefined;
    sponsor?: any;
    educationalAlignment?: any;
    isAccessibleForFree?: boolean | undefined;
    encodings?: any;
    accessModeSufficient?: any;
    usageInfo?: any;
    recordedAt?: any;
    character?: any;
    citation?: any;
    pattern?: any;
    copyrightNotice?: string | undefined;
    headline?: string | undefined;
    interactionStatistic?: any;
    mentions?: any;
    sdLicense?: any;
    encodingFormat?: string | undefined;
    materialExtent?: any;
    creditText?: string | undefined;
    learningResourceType?: any;
    teaches?: any;
    about?: any;
    inLanguage?: any;
    assesses?: any;
    acquireLicensePage?: any;
    releasedEvent?: any;
    audio?: any;
    accessibilityFeature?: string | undefined;
    comment?: any;
    hasPart?: any;
    associatedMedia?: any;
    position?: string | number | undefined;
    creativeWorkStatus?: any;
    isBasedOnUrl?: any;
    material?: any;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    editor?: any;
    workExample?: any;
    audience?: any;
    correction?: any;
    keywords?: any;
    publisherImprint?: any;
    isBasedOn?: any;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "HowToTip";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    text?: string | undefined;
    aggregateRating?: any;
    discussionUrl?: string | undefined;
    temporal?: string | undefined;
    conditionsOfAccess?: string | undefined;
    expires?: string | undefined;
    size?: any;
    timeRequired?: string | undefined;
    dateModified?: string | undefined;
    spatialCoverage?: any;
    educationalLevel?: any;
    exampleOfWork?: any;
    copyrightYear?: number | undefined;
    sourceOrganization?: any;
    isPartOf?: any;
    video?: any;
    workTranslation?: any;
    sdPublisher?: any;
    creator?: any;
    thumbnailUrl?: string | undefined;
    translationOfWork?: any;
    contentReferenceTime?: string | undefined;
    datePublished?: string | undefined;
    temporalCoverage?: any;
    fileFormat?: string | undefined;
    contentLocation?: any;
    alternativeHeadline?: string | undefined;
    contributor?: any;
    version?: string | number | undefined;
    accessMode?: string | undefined;
    spatial?: any;
    encoding?: any;
    producer?: any;
    abstract?: string | undefined;
    publication?: any;
    locationCreated?: any;
    maintainer?: any;
    copyrightHolder?: any;
    offers?: any;
    genre?: string | undefined;
    author?: any;
    accessibilitySummary?: string | undefined;
    dateCreated?: string | undefined;
    reviews?: any;
    contentRating?: any;
    accessibilityAPI?: string | undefined;
    publisher?: any;
    license?: any;
    isFamilyFriendly?: boolean | undefined;
    accessibilityHazard?: string | undefined;
    mainEntity?: any;
    award?: string | undefined;
    provider?: any;
    review?: any;
    accountablePerson?: any;
    interactivityType?: string | undefined;
    editEIDR?: string | undefined;
    translator?: any;
    commentCount?: number | undefined;
    schemaVersion?: string | undefined;
    sdDatePublished?: string | undefined;
    educationalUse?: any;
    accessibilityControl?: string | undefined;
    sponsor?: any;
    educationalAlignment?: any;
    isAccessibleForFree?: boolean | undefined;
    encodings?: any;
    accessModeSufficient?: any;
    usageInfo?: any;
    recordedAt?: any;
    character?: any;
    citation?: any;
    pattern?: any;
    copyrightNotice?: string | undefined;
    headline?: string | undefined;
    interactionStatistic?: any;
    mentions?: any;
    sdLicense?: any;
    encodingFormat?: string | undefined;
    materialExtent?: any;
    creditText?: string | undefined;
    learningResourceType?: any;
    teaches?: any;
    about?: any;
    inLanguage?: any;
    assesses?: any;
    acquireLicensePage?: any;
    releasedEvent?: any;
    audio?: any;
    accessibilityFeature?: string | undefined;
    comment?: any;
    hasPart?: any;
    associatedMedia?: any;
    position?: string | number | undefined;
    creativeWorkStatus?: any;
    isBasedOnUrl?: any;
    material?: any;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    editor?: any;
    workExample?: any;
    audience?: any;
    correction?: any;
    keywords?: any;
    publisherImprint?: any;
    isBasedOn?: any;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
