/**
 */
export const JobPosting: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "JobPosting";
} & {
    identifier?: any;
    title?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    applicationContact?: any;
    employerOverview?: string | undefined;
    educationRequirements?: any;
    skills?: any;
    estimatedSalary?: any;
    employmentType?: string | undefined;
    hiringOrganization?: any;
    sensoryRequirement?: any;
    industry?: any;
    jobStartDate?: string | undefined;
    jobImmediateStart?: boolean | undefined;
    employmentUnit?: any;
    securityClearanceRequirement?: string | undefined;
    responsibilities?: string | undefined;
    jobBenefits?: string | undefined;
    jobLocation?: any;
    applicantLocationRequirements?: any;
    occupationalCategory?: any;
    qualifications?: any;
    jobLocationType?: string | undefined;
    relevantOccupation?: any;
    incentiveCompensation?: string | undefined;
    datePosted?: string | undefined;
    physicalRequirement?: any;
    experienceRequirements?: any;
    experienceInPlaceOfEducation?: boolean | undefined;
    specialCommitments?: string | undefined;
    workHours?: string | undefined;
    totalJobOpenings?: number | undefined;
    salaryCurrency?: string | undefined;
    baseSalary?: any;
    benefits?: string | undefined;
    eligibilityToWorkRequirement?: string | undefined;
    validThrough?: string | undefined;
    incentives?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "JobPosting";
} & {
    identifier?: any;
    title?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    applicationContact?: any;
    employerOverview?: string | undefined;
    educationRequirements?: any;
    skills?: any;
    estimatedSalary?: any;
    employmentType?: string | undefined;
    hiringOrganization?: any;
    sensoryRequirement?: any;
    industry?: any;
    jobStartDate?: string | undefined;
    jobImmediateStart?: boolean | undefined;
    employmentUnit?: any;
    securityClearanceRequirement?: string | undefined;
    responsibilities?: string | undefined;
    jobBenefits?: string | undefined;
    jobLocation?: any;
    applicantLocationRequirements?: any;
    occupationalCategory?: any;
    qualifications?: any;
    jobLocationType?: string | undefined;
    relevantOccupation?: any;
    incentiveCompensation?: string | undefined;
    datePosted?: string | undefined;
    physicalRequirement?: any;
    experienceRequirements?: any;
    experienceInPlaceOfEducation?: boolean | undefined;
    specialCommitments?: string | undefined;
    workHours?: string | undefined;
    totalJobOpenings?: number | undefined;
    salaryCurrency?: string | undefined;
    baseSalary?: any;
    benefits?: string | undefined;
    eligibilityToWorkRequirement?: string | undefined;
    validThrough?: string | undefined;
    incentives?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
