/**
 */
export const LodgingReservation: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "LodgingReservation";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    checkinTime?: string | undefined;
    lodgingUnitType?: any;
    numChildren?: any;
    lodgingUnitDescription?: string | undefined;
    numAdults?: any;
    checkoutTime?: string | undefined;
    underName?: any;
    reservationStatus?: any;
    programMembershipUsed?: any;
    priceCurrency?: string | undefined;
    broker?: any;
    bookingTime?: string | undefined;
    provider?: any;
    reservationId?: string | undefined;
    modifiedTime?: string | undefined;
    totalPrice?: any;
    reservationFor?: any;
    bookingAgent?: any;
    reservedTicket?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "LodgingReservation";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    checkinTime?: string | undefined;
    lodgingUnitType?: any;
    numChildren?: any;
    lodgingUnitDescription?: string | undefined;
    numAdults?: any;
    checkoutTime?: string | undefined;
    underName?: any;
    reservationStatus?: any;
    programMembershipUsed?: any;
    priceCurrency?: string | undefined;
    broker?: any;
    bookingTime?: string | undefined;
    provider?: any;
    reservationId?: string | undefined;
    modifiedTime?: string | undefined;
    totalPrice?: any;
    reservationFor?: any;
    bookingAgent?: any;
    reservedTicket?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
