/**
 */
export const MedicalCondition: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "MedicalCondition";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    differentialDiagnosis?: any;
    epidemiology?: string | undefined;
    associatedAnatomy?: any;
    naturalProgression?: string | undefined;
    possibleTreatment?: any;
    secondaryPrevention?: any;
    status?: any;
    possibleComplication?: string | undefined;
    primaryPrevention?: any;
    drug?: any;
    signOrSymptom?: any;
    expectedPrognosis?: string | undefined;
    riskFactor?: any;
    stage?: any;
    typicalTest?: any;
    pathophysiology?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "MedicalCondition";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    differentialDiagnosis?: any;
    epidemiology?: string | undefined;
    associatedAnatomy?: any;
    naturalProgression?: string | undefined;
    possibleTreatment?: any;
    secondaryPrevention?: any;
    status?: any;
    possibleComplication?: string | undefined;
    primaryPrevention?: any;
    drug?: any;
    signOrSymptom?: any;
    expectedPrognosis?: string | undefined;
    riskFactor?: any;
    stage?: any;
    typicalTest?: any;
    pathophysiology?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
