/**
 */
export const MortgageLoan: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "MortgageLoan";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    domiciledMortgage?: boolean | undefined;
    loanMortgageMandateAmount?: any;
    gracePeriod?: string | undefined;
    amount?: any;
    loanType?: string | undefined;
    renegotiableLoan?: boolean | undefined;
    recourseLoan?: boolean | undefined;
    requiredCollateral?: any;
    loanRepaymentForm?: any;
    currency?: string | undefined;
    loanTerm?: any;
    feesAndCommissionsSpecification?: string | undefined;
    interestRate?: any;
    annualPercentageRate?: any;
    aggregateRating?: any;
    serviceOutput?: any;
    isSimilarTo?: any;
    offers?: any;
    broker?: any;
    termsOfService?: string | undefined;
    award?: string | undefined;
    provider?: any;
    review?: any;
    areaServed?: any;
    serviceAudience?: any;
    hasOfferCatalog?: any;
    produces?: any;
    logo?: any;
    availableChannel?: any;
    category?: any;
    serviceType?: any;
    slogan?: string | undefined;
    hoursAvailable?: any;
    serviceArea?: any;
    brand?: any;
    audience?: any;
    isRelatedTo?: any;
    providerMobility?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "MortgageLoan";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    domiciledMortgage?: boolean | undefined;
    loanMortgageMandateAmount?: any;
    gracePeriod?: string | undefined;
    amount?: any;
    loanType?: string | undefined;
    renegotiableLoan?: boolean | undefined;
    recourseLoan?: boolean | undefined;
    requiredCollateral?: any;
    loanRepaymentForm?: any;
    currency?: string | undefined;
    loanTerm?: any;
    feesAndCommissionsSpecification?: string | undefined;
    interestRate?: any;
    annualPercentageRate?: any;
    aggregateRating?: any;
    serviceOutput?: any;
    isSimilarTo?: any;
    offers?: any;
    broker?: any;
    termsOfService?: string | undefined;
    award?: string | undefined;
    provider?: any;
    review?: any;
    areaServed?: any;
    serviceAudience?: any;
    hasOfferCatalog?: any;
    produces?: any;
    logo?: any;
    availableChannel?: any;
    category?: any;
    serviceType?: any;
    slogan?: string | undefined;
    hoursAvailable?: any;
    serviceArea?: any;
    brand?: any;
    audience?: any;
    isRelatedTo?: any;
    providerMobility?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
