/**
 */
export const Muscle: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Muscle";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    nerve?: any;
    antagonist?: any;
    muscleAction?: string | undefined;
    bloodSupply?: any;
    insertion?: any;
    associatedPathophysiology?: string | undefined;
    connectedTo?: any;
    relatedTherapy?: any;
    relatedCondition?: any;
    subStructure?: any;
    partOfSystem?: any;
    bodyLocation?: string | undefined;
    diagram?: any;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Muscle";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    nerve?: any;
    antagonist?: any;
    muscleAction?: string | undefined;
    bloodSupply?: any;
    insertion?: any;
    associatedPathophysiology?: string | undefined;
    connectedTo?: any;
    relatedTherapy?: any;
    relatedCondition?: any;
    subStructure?: any;
    partOfSystem?: any;
    bodyLocation?: string | undefined;
    diagram?: any;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
