/**
 */
export const OccupationalTherapy: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "OccupationalTherapy";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    seriousAdverseOutcome?: any;
    contraindication?: any;
    duplicateTherapy?: any;
    drug?: any;
    adverseOutcome?: any;
    doseSchedule?: any;
    preparation?: any;
    followup?: string | undefined;
    howPerformed?: string | undefined;
    status?: any;
    procedureType?: any;
    bodyLocation?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "OccupationalTherapy";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    seriousAdverseOutcome?: any;
    contraindication?: any;
    duplicateTherapy?: any;
    drug?: any;
    adverseOutcome?: any;
    doseSchedule?: any;
    preparation?: any;
    followup?: string | undefined;
    howPerformed?: string | undefined;
    status?: any;
    procedureType?: any;
    bodyLocation?: string | undefined;
    guideline?: any;
    recognizingAuthority?: any;
    legalStatus?: any;
    code?: any;
    relevantSpecialty?: any;
    study?: any;
    medicineSystem?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
