/**
 */
export const Order: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Order";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    isGift?: boolean | undefined;
    orderDelivery?: any;
    customer?: any;
    acceptedOffer?: any;
    discountCurrency?: string | undefined;
    seller?: any;
    paymentDue?: string | undefined;
    confirmationNumber?: string | undefined;
    orderNumber?: string | undefined;
    paymentMethodId?: string | undefined;
    billingAddress?: any;
    broker?: any;
    paymentUrl?: string | undefined;
    partOfInvoice?: any;
    paymentDueDate?: string | undefined;
    merchant?: any;
    orderedItem?: any;
    orderDate?: string | undefined;
    paymentMethod?: any;
    discountCode?: string | undefined;
    orderStatus?: any;
    discount?: string | number | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Order";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    isGift?: boolean | undefined;
    orderDelivery?: any;
    customer?: any;
    acceptedOffer?: any;
    discountCurrency?: string | undefined;
    seller?: any;
    paymentDue?: string | undefined;
    confirmationNumber?: string | undefined;
    orderNumber?: string | undefined;
    paymentMethodId?: string | undefined;
    billingAddress?: any;
    broker?: any;
    paymentUrl?: string | undefined;
    partOfInvoice?: any;
    paymentDueDate?: string | undefined;
    merchant?: any;
    orderedItem?: any;
    orderDate?: string | undefined;
    paymentMethod?: any;
    discountCode?: string | undefined;
    orderStatus?: any;
    discount?: string | number | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
