/**
 */
export const Organization: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Organization";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    aggregateRating?: any;
    diversityStaffingReport?: any;
    numberOfEmployees?: any;
    employees?: any;
    address?: any;
    correctionsPolicy?: any;
    ownershipFundingInfo?: any;
    globalLocationNumber?: string | undefined;
    knowsAbout?: any;
    contactPoint?: any;
    knowsLanguage?: any;
    leiCode?: string | undefined;
    founder?: any;
    department?: any;
    alumni?: any;
    members?: any;
    employee?: any;
    subOrganization?: any;
    vatID?: string | undefined;
    nonprofitStatus?: any;
    duns?: string | undefined;
    hasMerchantReturnPolicy?: any;
    contactPoints?: any;
    unnamedSourcesPolicy?: any;
    founders?: any;
    makesOffer?: any;
    isicV4?: string | undefined;
    reviews?: any;
    award?: string | undefined;
    review?: any;
    events?: any;
    areaServed?: any;
    dissolutionDate?: string | undefined;
    member?: any;
    seeks?: any;
    hasOfferCatalog?: any;
    event?: any;
    email?: string | undefined;
    legalName?: string | undefined;
    sponsor?: any;
    telephone?: string | undefined;
    foundingDate?: string | undefined;
    logo?: any;
    parentOrganization?: any;
    ethicsPolicy?: any;
    slogan?: string | undefined;
    owns?: any;
    interactionStatistic?: any;
    serviceArea?: any;
    actionableFeedbackPolicy?: any;
    faxNumber?: string | undefined;
    memberOf?: any;
    hasCredential?: any;
    brand?: any;
    diversityPolicy?: any;
    taxID?: string | undefined;
    naics?: string | undefined;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    location?: any;
    hasPOS?: any;
    foundingLocation?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Organization";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    aggregateRating?: any;
    diversityStaffingReport?: any;
    numberOfEmployees?: any;
    employees?: any;
    address?: any;
    correctionsPolicy?: any;
    ownershipFundingInfo?: any;
    globalLocationNumber?: string | undefined;
    knowsAbout?: any;
    contactPoint?: any;
    knowsLanguage?: any;
    leiCode?: string | undefined;
    founder?: any;
    department?: any;
    alumni?: any;
    members?: any;
    employee?: any;
    subOrganization?: any;
    vatID?: string | undefined;
    nonprofitStatus?: any;
    duns?: string | undefined;
    hasMerchantReturnPolicy?: any;
    contactPoints?: any;
    unnamedSourcesPolicy?: any;
    founders?: any;
    makesOffer?: any;
    isicV4?: string | undefined;
    reviews?: any;
    award?: string | undefined;
    review?: any;
    events?: any;
    areaServed?: any;
    dissolutionDate?: string | undefined;
    member?: any;
    seeks?: any;
    hasOfferCatalog?: any;
    event?: any;
    email?: string | undefined;
    legalName?: string | undefined;
    sponsor?: any;
    telephone?: string | undefined;
    foundingDate?: string | undefined;
    logo?: any;
    parentOrganization?: any;
    ethicsPolicy?: any;
    slogan?: string | undefined;
    owns?: any;
    interactionStatistic?: any;
    serviceArea?: any;
    actionableFeedbackPolicy?: any;
    faxNumber?: string | undefined;
    memberOf?: any;
    hasCredential?: any;
    brand?: any;
    diversityPolicy?: any;
    taxID?: string | undefined;
    naics?: string | undefined;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    location?: any;
    hasPOS?: any;
    foundingLocation?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
