/**
 */
export const Person: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "Person";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    follows?: any;
    workLocation?: any;
    affiliation?: any;
    height?: any;
    worksFor?: any;
    address?: any;
    honorificPrefix?: string | undefined;
    globalLocationNumber?: string | undefined;
    knowsAbout?: any;
    contactPoint?: any;
    jobTitle?: any;
    knowsLanguage?: any;
    hasOccupation?: any;
    performerIn?: any;
    weight?: any;
    homeLocation?: any;
    gender?: any;
    spouse?: any;
    siblings?: any;
    givenName?: string | undefined;
    vatID?: string | undefined;
    duns?: string | undefined;
    colleague?: any;
    contactPoints?: any;
    makesOffer?: any;
    isicV4?: string | undefined;
    award?: string | undefined;
    familyName?: string | undefined;
    netWorth?: any;
    seeks?: any;
    hasOfferCatalog?: any;
    birthDate?: string | undefined;
    children?: any;
    email?: string | undefined;
    sponsor?: any;
    telephone?: string | undefined;
    birthPlace?: any;
    honorificSuffix?: string | undefined;
    colleagues?: any;
    alumniOf?: any;
    owns?: any;
    interactionStatistic?: any;
    deathDate?: string | undefined;
    additionalName?: string | undefined;
    faxNumber?: string | undefined;
    knows?: any;
    memberOf?: any;
    sibling?: any;
    deathPlace?: any;
    hasCredential?: any;
    parents?: any;
    relatedTo?: any;
    brand?: any;
    taxID?: string | undefined;
    nationality?: any;
    naics?: string | undefined;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    callSign?: string | undefined;
    parent?: any;
    hasPOS?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "Person";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    follows?: any;
    workLocation?: any;
    affiliation?: any;
    height?: any;
    worksFor?: any;
    address?: any;
    honorificPrefix?: string | undefined;
    globalLocationNumber?: string | undefined;
    knowsAbout?: any;
    contactPoint?: any;
    jobTitle?: any;
    knowsLanguage?: any;
    hasOccupation?: any;
    performerIn?: any;
    weight?: any;
    homeLocation?: any;
    gender?: any;
    spouse?: any;
    siblings?: any;
    givenName?: string | undefined;
    vatID?: string | undefined;
    duns?: string | undefined;
    colleague?: any;
    contactPoints?: any;
    makesOffer?: any;
    isicV4?: string | undefined;
    award?: string | undefined;
    familyName?: string | undefined;
    netWorth?: any;
    seeks?: any;
    hasOfferCatalog?: any;
    birthDate?: string | undefined;
    children?: any;
    email?: string | undefined;
    sponsor?: any;
    telephone?: string | undefined;
    birthPlace?: any;
    honorificSuffix?: string | undefined;
    colleagues?: any;
    alumniOf?: any;
    owns?: any;
    interactionStatistic?: any;
    deathDate?: string | undefined;
    additionalName?: string | undefined;
    faxNumber?: string | undefined;
    knows?: any;
    memberOf?: any;
    sibling?: any;
    deathPlace?: any;
    hasCredential?: any;
    parents?: any;
    relatedTo?: any;
    brand?: any;
    taxID?: string | undefined;
    nationality?: any;
    naics?: string | undefined;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    callSign?: string | undefined;
    parent?: any;
    hasPOS?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
