/**
 */
export const RsvpAction: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "RsvpAction";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    additionalNumberOfGuests?: number | undefined;
    rsvpResponse?: any;
    comment?: any;
    event?: any;
    recipient?: any;
    language?: any;
    about?: any;
    inLanguage?: any;
    startTime?: string | undefined;
    instrument?: any;
    actionStatus?: any;
    agent?: any;
    participant?: any;
    target?: any;
    endTime?: string | undefined;
    error?: any;
    result?: any;
    object?: any;
    location?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "RsvpAction";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    additionalNumberOfGuests?: number | undefined;
    rsvpResponse?: any;
    comment?: any;
    event?: any;
    recipient?: any;
    language?: any;
    about?: any;
    inLanguage?: any;
    startTime?: string | undefined;
    instrument?: any;
    actionStatus?: any;
    agent?: any;
    participant?: any;
    target?: any;
    endTime?: string | undefined;
    error?: any;
    result?: any;
    object?: any;
    location?: any;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
