/**
 */
export const SomeProducts: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "SomeProducts";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    inventoryLevel?: any;
    hasMeasurement?: any;
    itemCondition?: any;
    aggregateRating?: any;
    size?: any;
    depth?: any;
    height?: any;
    gtin12?: string | undefined;
    isSimilarTo?: any;
    weight?: any;
    hasMerchantReturnPolicy?: any;
    offers?: any;
    width?: any;
    isConsumableFor?: any;
    reviews?: any;
    award?: string | undefined;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    review?: any;
    hasEnergyConsumptionDetails?: any;
    color?: string | undefined;
    additionalProperty?: any;
    logo?: any;
    mpn?: string | undefined;
    inProductGroupWithID?: string | undefined;
    category?: any;
    isVariantOf?: any;
    slogan?: string | undefined;
    pattern?: any;
    sku?: string | undefined;
    nsn?: string | undefined;
    purchaseDate?: string | undefined;
    gtin14?: string | undefined;
    isAccessoryOrSparePartFor?: any;
    manufacturer?: any;
    model?: any;
    brand?: any;
    releaseDate?: string | undefined;
    gtin8?: string | undefined;
    material?: any;
    productionDate?: string | undefined;
    awards?: string | undefined;
    audience?: any;
    isRelatedTo?: any;
    productID?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "SomeProducts";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    inventoryLevel?: any;
    hasMeasurement?: any;
    itemCondition?: any;
    aggregateRating?: any;
    size?: any;
    depth?: any;
    height?: any;
    gtin12?: string | undefined;
    isSimilarTo?: any;
    weight?: any;
    hasMerchantReturnPolicy?: any;
    offers?: any;
    width?: any;
    isConsumableFor?: any;
    reviews?: any;
    award?: string | undefined;
    gtin13?: string | undefined;
    gtin?: string | undefined;
    review?: any;
    hasEnergyConsumptionDetails?: any;
    color?: string | undefined;
    additionalProperty?: any;
    logo?: any;
    mpn?: string | undefined;
    inProductGroupWithID?: string | undefined;
    category?: any;
    isVariantOf?: any;
    slogan?: string | undefined;
    pattern?: any;
    sku?: string | undefined;
    nsn?: string | undefined;
    purchaseDate?: string | undefined;
    gtin14?: string | undefined;
    isAccessoryOrSparePartFor?: any;
    manufacturer?: any;
    model?: any;
    brand?: any;
    releaseDate?: string | undefined;
    gtin8?: string | undefined;
    material?: any;
    productionDate?: string | undefined;
    awards?: string | undefined;
    audience?: any;
    isRelatedTo?: any;
    productID?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
