/**
 */
export const VideoObject: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "VideoObject";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    directors?: any;
    thumbnail?: any;
    transcript?: string | undefined;
    videoFrameSize?: string | undefined;
    actor?: any;
    director?: any;
    musicBy?: any;
    videoQuality?: string | undefined;
    caption?: any;
    actors?: any;
    startTime?: string | undefined;
    bitrate?: string | undefined;
    height?: any;
    playerType?: string | undefined;
    embedUrl?: string | undefined;
    width?: any;
    encodesCreativeWork?: any;
    regionsAllowed?: any;
    endTime?: string | undefined;
    ineligibleRegion?: any;
    uploadDate?: string | undefined;
    contentUrl?: string | undefined;
    contentSize?: string | undefined;
    encodingFormat?: string | undefined;
    productionCompany?: any;
    associatedArticle?: any;
    duration?: string | undefined;
    requiresSubscription?: any;
    text?: string | undefined;
    aggregateRating?: any;
    discussionUrl?: string | undefined;
    temporal?: string | undefined;
    conditionsOfAccess?: string | undefined;
    expires?: string | undefined;
    size?: any;
    timeRequired?: string | undefined;
    dateModified?: string | undefined;
    spatialCoverage?: any;
    educationalLevel?: any;
    exampleOfWork?: any;
    copyrightYear?: number | undefined;
    sourceOrganization?: any;
    isPartOf?: any;
    video?: any;
    workTranslation?: any;
    sdPublisher?: any;
    creator?: any;
    thumbnailUrl?: string | undefined;
    translationOfWork?: any;
    contentReferenceTime?: string | undefined;
    datePublished?: string | undefined;
    temporalCoverage?: any;
    fileFormat?: string | undefined;
    contentLocation?: any;
    alternativeHeadline?: string | undefined;
    contributor?: any;
    version?: string | number | undefined;
    accessMode?: string | undefined;
    spatial?: any;
    encoding?: any;
    producer?: any;
    abstract?: string | undefined;
    publication?: any;
    locationCreated?: any;
    maintainer?: any;
    copyrightHolder?: any;
    offers?: any;
    genre?: string | undefined;
    author?: any;
    accessibilitySummary?: string | undefined;
    dateCreated?: string | undefined;
    reviews?: any;
    contentRating?: any;
    accessibilityAPI?: string | undefined;
    publisher?: any;
    license?: any;
    isFamilyFriendly?: boolean | undefined;
    accessibilityHazard?: string | undefined;
    mainEntity?: any;
    award?: string | undefined;
    provider?: any;
    review?: any;
    accountablePerson?: any;
    interactivityType?: string | undefined;
    editEIDR?: string | undefined;
    translator?: any;
    commentCount?: number | undefined;
    schemaVersion?: string | undefined;
    sdDatePublished?: string | undefined;
    educationalUse?: any;
    accessibilityControl?: string | undefined;
    sponsor?: any;
    educationalAlignment?: any;
    isAccessibleForFree?: boolean | undefined;
    encodings?: any;
    accessModeSufficient?: any;
    usageInfo?: any;
    recordedAt?: any;
    character?: any;
    citation?: any;
    pattern?: any;
    copyrightNotice?: string | undefined;
    headline?: string | undefined;
    interactionStatistic?: any;
    mentions?: any;
    sdLicense?: any;
    materialExtent?: any;
    creditText?: string | undefined;
    learningResourceType?: any;
    teaches?: any;
    about?: any;
    inLanguage?: any;
    assesses?: any;
    acquireLicensePage?: any;
    releasedEvent?: any;
    audio?: any;
    accessibilityFeature?: string | undefined;
    comment?: any;
    hasPart?: any;
    associatedMedia?: any;
    position?: string | number | undefined;
    creativeWorkStatus?: any;
    isBasedOnUrl?: any;
    material?: any;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    editor?: any;
    workExample?: any;
    audience?: any;
    correction?: any;
    keywords?: any;
    publisherImprint?: any;
    isBasedOn?: any;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "VideoObject";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    directors?: any;
    thumbnail?: any;
    transcript?: string | undefined;
    videoFrameSize?: string | undefined;
    actor?: any;
    director?: any;
    musicBy?: any;
    videoQuality?: string | undefined;
    caption?: any;
    actors?: any;
    startTime?: string | undefined;
    bitrate?: string | undefined;
    height?: any;
    playerType?: string | undefined;
    embedUrl?: string | undefined;
    width?: any;
    encodesCreativeWork?: any;
    regionsAllowed?: any;
    endTime?: string | undefined;
    ineligibleRegion?: any;
    uploadDate?: string | undefined;
    contentUrl?: string | undefined;
    contentSize?: string | undefined;
    encodingFormat?: string | undefined;
    productionCompany?: any;
    associatedArticle?: any;
    duration?: string | undefined;
    requiresSubscription?: any;
    text?: string | undefined;
    aggregateRating?: any;
    discussionUrl?: string | undefined;
    temporal?: string | undefined;
    conditionsOfAccess?: string | undefined;
    expires?: string | undefined;
    size?: any;
    timeRequired?: string | undefined;
    dateModified?: string | undefined;
    spatialCoverage?: any;
    educationalLevel?: any;
    exampleOfWork?: any;
    copyrightYear?: number | undefined;
    sourceOrganization?: any;
    isPartOf?: any;
    video?: any;
    workTranslation?: any;
    sdPublisher?: any;
    creator?: any;
    thumbnailUrl?: string | undefined;
    translationOfWork?: any;
    contentReferenceTime?: string | undefined;
    datePublished?: string | undefined;
    temporalCoverage?: any;
    fileFormat?: string | undefined;
    contentLocation?: any;
    alternativeHeadline?: string | undefined;
    contributor?: any;
    version?: string | number | undefined;
    accessMode?: string | undefined;
    spatial?: any;
    encoding?: any;
    producer?: any;
    abstract?: string | undefined;
    publication?: any;
    locationCreated?: any;
    maintainer?: any;
    copyrightHolder?: any;
    offers?: any;
    genre?: string | undefined;
    author?: any;
    accessibilitySummary?: string | undefined;
    dateCreated?: string | undefined;
    reviews?: any;
    contentRating?: any;
    accessibilityAPI?: string | undefined;
    publisher?: any;
    license?: any;
    isFamilyFriendly?: boolean | undefined;
    accessibilityHazard?: string | undefined;
    mainEntity?: any;
    award?: string | undefined;
    provider?: any;
    review?: any;
    accountablePerson?: any;
    interactivityType?: string | undefined;
    editEIDR?: string | undefined;
    translator?: any;
    commentCount?: number | undefined;
    schemaVersion?: string | undefined;
    sdDatePublished?: string | undefined;
    educationalUse?: any;
    accessibilityControl?: string | undefined;
    sponsor?: any;
    educationalAlignment?: any;
    isAccessibleForFree?: boolean | undefined;
    encodings?: any;
    accessModeSufficient?: any;
    usageInfo?: any;
    recordedAt?: any;
    character?: any;
    citation?: any;
    pattern?: any;
    copyrightNotice?: string | undefined;
    headline?: string | undefined;
    interactionStatistic?: any;
    mentions?: any;
    sdLicense?: any;
    materialExtent?: any;
    creditText?: string | undefined;
    learningResourceType?: any;
    teaches?: any;
    about?: any;
    inLanguage?: any;
    assesses?: any;
    acquireLicensePage?: any;
    releasedEvent?: any;
    audio?: any;
    accessibilityFeature?: string | undefined;
    comment?: any;
    hasPart?: any;
    associatedMedia?: any;
    position?: string | number | undefined;
    creativeWorkStatus?: any;
    isBasedOnUrl?: any;
    material?: any;
    funder?: any;
    publishingPrinciples?: any;
    awards?: string | undefined;
    editor?: any;
    workExample?: any;
    audience?: any;
    correction?: any;
    keywords?: any;
    publisherImprint?: any;
    isBasedOn?: any;
    typicalAgeRange?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
