/**
 */
export const VideoGameSeries: import("@imin/speck/lib/types").ObjectSpeck<{
    '@type': "VideoGameSeries";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    directors?: any;
    numberOfPlayers?: any;
    seasons?: any;
    season?: any;
    playMode?: any;
    actor?: any;
    numberOfSeasons?: number | undefined;
    gameLocation?: any;
    director?: any;
    musicBy?: any;
    numberOfEpisodes?: number | undefined;
    episodes?: any;
    gameItem?: any;
    gamePlatform?: any;
    characterAttribute?: any;
    actors?: any;
    containsSeason?: any;
    quest?: any;
    episode?: any;
    productionCompany?: any;
    trailer?: any;
    cheatCode?: any;
    startDate?: string | undefined;
    issn?: string | undefined;
    endDate?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}, {
    '@type': "VideoGameSeries";
} & {
    identifier?: any;
    name?: string | undefined;
    description?: string | undefined;
    directors?: any;
    numberOfPlayers?: any;
    seasons?: any;
    season?: any;
    playMode?: any;
    actor?: any;
    numberOfSeasons?: number | undefined;
    gameLocation?: any;
    director?: any;
    musicBy?: any;
    numberOfEpisodes?: number | undefined;
    episodes?: any;
    gameItem?: any;
    gamePlatform?: any;
    characterAttribute?: any;
    actors?: any;
    containsSeason?: any;
    quest?: any;
    episode?: any;
    productionCompany?: any;
    trailer?: any;
    cheatCode?: any;
    startDate?: string | undefined;
    issn?: string | undefined;
    endDate?: string | undefined;
    sameAs?: string | undefined;
    subjectOf?: any;
    potentialAction?: any;
    mainEntityOfPage?: any;
    additionalType?: string | undefined;
    alternateName?: string | undefined;
    url?: string | undefined;
    image?: any;
    disambiguatingDescription?: string | undefined;
}>;
