name: Update Data Model

on:
  workflow_dispatch:
  repository_dispatch:
    types: [data-models-update]
  workflow_call:
    inputs:
      data-models_ref:
        required: false
        type: string
      models-lib_ref:
        required: false
        type: string
      models-ts_ref:
        required: false
        type: string
        default: 'refs/heads/main'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout models-ts
        uses: actions/checkout@v2
        with:
          path: models-ts
          # If this is being called from another workflow, then the models-ts_ref will be provided or defaulted; otherwise we can assume a different trigger
          ref: ${{ inputs.models-ts_ref || github.ref }}

      - name: Checkout models-lib
        uses: actions/checkout@v2
        with:
          repository: openactive/models-lib
          path: models-lib
          ref: ${{ inputs.models-lib_ref || 'refs/heads/main' }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        
      - name: Install models-lib
        run: npm install
        working-directory: ./models-lib/
        
      - name: Update models-lib with latest data-models
        if: ${{ !inputs.data-models_ref }}
        run: npm update @openactive/data-models
        working-directory: ./models-lib/

      - name: Install specific version of data-models ${{ inputs.data-models_ref }}
        if: ${{ inputs.data-models_ref }}
        run: npm install github:openactive/data-models#${{ inputs.data-models_ref }}

      - name: Run TypeScript models generator
        run: npm start -- generate TypeScript --destination ../models-ts/src/
        working-directory: ./models-lib/
        
      - name: Install models-ts
        run: npm install
        working-directory: ./models-ts/
        
      - name: Build models-ts types
        run: npm run build
        working-directory: ./models-ts/

      - name: Upload current state of branch
        uses: actions/upload-artifact@v4
        if: ${{ inputs.data-models_ref || inputs.models-lib_ref || inputs.models-ts_ref }}
        with:
          name: models-ts
          path: models-ts

      - name: Test current state of branch
        uses: openactive/models-ts/.github/workflows/tests.yaml@${{ inputs.models-ts_ref || github.ref }}
        if: ${{ inputs.data-models_ref || inputs.models-lib_ref || inputs.models-ts_ref }}
        with:
          repo_artifact: models-ts
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        if: ${{ !inputs.data-models_ref && !inputs.models-lib_ref && !inputs.models-ts_ref }}
        with:
          path: ./models-ts/
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          commit-message: Update data models
          committer: openactive-bot <openactive-bot@users.noreply.github.com>
          author: openactive-bot <openactive-bot@users.noreply.github.com>
          signoff: false
          branch: ci/update-data-models
          delete-branch: true
          title: 'Update data models'
          body: |
            Update JavaScript/TypeScript data models to the latest version based on the [OpenActive Vocabulary](https://openactive.io/ns/) (codified by the [Data Models](https://github.com/openactive/data-models)), [Test Interface](https://openactive.io/test-interface/) and [Beta Namespace](https://openactive.io/ns-beta/).
          labels: |
            automated pr
          draft: false

      - name: Check outputs
        if: ${{ !inputs.data-models_ref && !inputs.models-lib_ref && !inputs.models-ts_ref }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
